name: Rust Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Cache Cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build project
      run: cargo build --release

    - name: Create release artifact
      run: |
        mkdir -p release
        cp target/release/renamers release/
    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: renamers
        path: release/renamers

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: renamers

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/renamers
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

